name: Build, Push to ECR, and Deploy with Helm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Extract repository name and image tag
      id: extract
      run: |
        echo "REPOSITORY_URI=${{ secrets.ECR_REPOSITORY_URI }}" >> $GITHUB_ENV
        echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

    - name: Build and push Docker image
      run: |
        docker build -t ${{ env.REPOSITORY_URI }}:${{ env.IMAGE_TAG }} .
        docker push ${{ env.REPOSITORY_URI }}:${{ env.IMAGE_TAG }}

    - name: Configure kubectl
      run: |
        aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name vidtoascii-cluster

    - name: Deploy with Helm (Development)
      run: |
        helm upgrade --install vidtoasciihelm ./vidtoasciihelm \
          --set image.repository=${{ env.REPOSITORY_URI }} \
          --set image.tag=${{ env.IMAGE_TAG }} \
          --values ./vidtoasciihelm/values.yaml

    - name: Deploy with Helm (Production)
      run: |
        helm upgrade --install vidtoasciihelm-prod ./vidtoasciihelm \
          --set image.repository=${{ env.REPOSITORY_URI }} \
          --set image.tag=${{ env.IMAGE_TAG }} \
          --values ./vidtoasciihelm/values-prod.yaml
